### PR TITLE
fix: TextTheme.body1 was replaced by bodyText1 as it failed in newer versions

### PR DESCRIPTION
**Pull request by nombrekeff**
Hey there!

I use this plugin on a project at work, we just updated Flutter, and the build failed because of invalid TextTheme property `body1`. 

### Description
Replaces `TextTheme.body1` with `TextTheme.bodyText1`

> PD: Are you maintaining the project? or would I be able to help out? Otherwise is there any problem in me making a clone so I can maintain it for work?

### CODE REVIEW

**Comment by nombrekeff** [comment]
Sorry, pubspec.lock was uploaded on error, I will remove it

**Comment by nombrekeff** [comment]
It's not yet working, dependency issues, I will do some tests and let you know when I find the solution.

**Comment by nombrekeff** [comment]
> It's not yet working, dependency issues, I will do some tests and let you know when I find the solution.

Okay, I've tested and this works with Flutter `v2.4.0`

**Comment by blackmann** [comment]
Hello, thanks for the contribution. Could you please compare to the null safety branch instead?
@nombrekeff

**Comment by nombrekeff** [comment]
Ohh sure, I did not know there was one!

**Pull request closed without merging**
