### PR TITLE
Refactor and Code split

### PR DESCRIPTION
**Pull request by jogboms**
I didn't really refactor much though. I just felt the need separate the widgets so I could see clearly. 

We could still refactor to improve code quality and review together. One way is introducing a lint file.

NB: I use a line width of 120. Makes code more readable.

### CODE REVIEW

**Comment by jogboms** [comment]
@blackmann done

**Comment by blackmann** [comment]
Yes yes... I really liked the style. I'll merge it then we proceed to talk about the improvements you have in mind @jogboms 

Thanks very much.

**Comment by jogboms** [comment]
Awesome! 
Do you use twitter? We can also discuss there outside of github. I’m @jogboms also on Twitter.

**Comment by blackmann** [comment]
Oh, I'm off all socials except instagram (me_degreat). Or we can discord  (notgr#2262) we can have voice chats preferably

**Pull request merged**
