### PR TITLE
Feature/localization

### PR DESCRIPTION
**Pull request by daverupp**
I added a new localization file with default english setting.
When someone wants it to have in a different language, he can send a long a localized LocalizationItem with the appropriate language_code. Then also the google maps api search results will be translated accordingly.

the second commit is to have a back button in the appBar. In case you want to go back without a selection.
Of course you can ignore the second commit, then I will put the place_picker in its own scaffold and put an appbar on top of it to have the back button 👍 

thx for checking my enhancement and wish you a lovely day.
cheers dave

### CODE REVIEW

**Comment by blackmann** [comment]
Hi @daverupp , great work. I will be happy to merge this.

On the topic of the back icon, the initial design supposed the user was going to use the back gesture of their device. And the back icon makes an uncomfortable right align of the search field in (my opinion/eyes haha).

What do you think?

**Comment by daverupp** [comment]
Hey hey. Super happy to hear you like the localization approach.
I am not that into user experience on mobiles since I did more web development up to now. When the normal iOS behavior is also swiping from left to right to go back (I think the back button you only have on android) then it is fine.

or what you could do is, to extend the constructor with some ui options to toggle on off to leave it open to the dev using the lib.
but up to you :) As I already wrote, I have a workaround for that :) Just put it into a scaffold with a title.

thx again for taking my improvements into account.
cheers dave

**Comment by daverupp** [comment]
@blackmann Hey hey :) When do you plan to integrate the localization pull-request? In near future I plan to go live with my app and it would be super cool, if it is localized :)

**Comment by blackmann** [comment]
It is merged now @daverupp 

Thank you very much.

**Comment by blackmann** [comment]
This PR addresses #37 and has been merged

**Pull request closed without merging**
